name: Build TurboSnake

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build-turbosnake:
    name: Build TurboSnake with Turbo C++ 3.0 in DOSBox
    runs-on: ubuntu-latest

    env:
      ORIGINAL_FILENAME: "PIXGAMA2 copia.CPP"
      RENAMED_FILENAME: "game.cpp"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # - name: Install DOSBox
    #   run: sudo apt update && sudo apt install -y dosbox zip unzip

    # - name: Show DOSBox version and DOS version inside DOSBox
    #   run: |
    #     echo "=== DOSBox Version ==="
    #     dosbox -version || echo "DOSBox doesn't support -version, using workaround"
    #     echo "=== DOS (or MS-DOS) Version ==="
    #     dosbox -c "ver" -c "exit" | head -n 20 || true

    # - name: Create build folder
    #   run: |
    #     mkdir -p dos/cpp
    #     cp -r "src/$ORIGINAL_FILENAME" "dos/cpp/$RENAMED_FILENAME"
    #     cp -r tools dos/turbo

    # - name: Create autoexec config
    #   run: |
    #     echo "mount c ./dos" > autoexec.conf
    #     echo "c:" >> autoexec.conf
    #     echo "cd \\turbo\\bin" >> autoexec.conf
    #     echo "tcc \\cpp\\${RENAMED_FILENAME^^}" >> autoexec.conf
    #     echo "exit" >> autoexec.conf

    # - name: Show autoexec.conf contents
    #   run: cat autoexec.conf

    # - name: Run DOSBox with Turbo C++
    #   run: dosbox -conf autoexec.conf

    - name: 'Install dosbox-x (apt)'
      run: sudo snap install dosbox-x

    - name: Create build folder
      run: |
        mkdir -p build
        cp -r "src/$ORIGINAL_FILENAME" "build/$RENAMED_FILENAME"

    - name: 'Compile'
      uses: 'joncloud/dos-build-action@main'
      timeout-minutes: 2
      with:
        programs: |
          $/turbo-c++/3.00:c:\tc
          build:c:\build
        run: |
          c:
          cd \build
          tcc ${RENAMED_FILENAME}
        conf: |
          [dosbox]
          memsize=256

          [cpu]
          cycles=max
          turbo=true

    - name: Show build directory contents
      run: ls -la build

    - name: Archive result
      run: |
        mkdir -p output
        cp build/${RENAMED_FILENAME%.*}.EXE output/
        zip -j output.zip output/*

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: turbosnake-exe
        path: output.zip
