name: Build TurboSnake

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build-turbosnake:
    name: Build TurboSnake with Turbo C++ 3.0 in DOSBox-X
    runs-on: ubuntu-latest

    env:
      ORIGINAL_FILENAME: "PIXGAMA2 copia.CPP"
      RENAMED_FILENAME: "game.cpp"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install DOSBox-X using Snap
      run: sudo snap install dosbox-x

    - name: Create build folder
      run: |
        mkdir -p build
        cp src/*.cpp src/*.h build/
        ls -la build

    # This step creates the run commands to be executed in DOSBox-X
    # and replaces the ${RENAMED_FILENAME} variable with the actual filename
    # then the commands are stored in the `run_commands` output variable
    - name: Prepare run commands
      id: run
      run: |
        echo "run_commands<<EOF" >> $GITHUB_OUTPUT
        echo "c:" >> $GITHUB_OUTPUT
        echo "cd \\build" >> $GITHUB_OUTPUT
        echo "dir" >> $GITHUB_OUTPUT
        echo "tcc main.cpp game.cpp -egame > compile.log 2>&1" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Show run commands
      run: echo "${{ steps.run.outputs.run_commands }}"

    - name: Compile using Turbo C++ in DOSBox-X
      uses: joncloud/dos-build-action@main
      timeout-minutes: 2
      with:
        programs: |
          $/turbo-c++/3.00:c:\tc
          build:c:\build
        run: "${{ steps.run.outputs.run_commands }}"
        conf: |
          [dosbox]
          memsize=256

          [cpu]
          cycles=max
          turbo=true

    - name: Show build directory contents
      run: |
        ls -la build
        cat build/compile.log

    - name: Artifact path setup
      run: |
        BASENAME="${RENAMED_FILENAME%.*}"
        EXENAME="${BASENAME^^}.EXE"
        echo "artifactPath=build/$EXENAME" >> $GITHUB_ENV

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: turbosnake-exe
        path: ${{ env.artifactPath }}
        compression-level: 9 # maximum compression
