name: Build TurboSnake

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build-turbosnake:
    name: Build TurboSnake with Turbo C++ 3.0 in DOSBox
    runs-on: ubuntu-latest

    env:
      ORIGINAL_FILENAME: "PIXGAMA2 copia.CPP"
      RENAMED_FILENAME: "game.cpp"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: 'Install dosbox-x'
      run: sudo snap install dosbox-x

    - name: Create build folder
      run: |
        mkdir -p build
        cp -r "src/$ORIGINAL_FILENAME" "build/$RENAMED_FILENAME"

    - name: 'Compile'
      uses: 'joncloud/dos-build-action@main'
      timeout-minutes: 2
      with:
        programs: |
          $/turbo-c++/3.00:c:\tc
          build:c:\build
        run: |
          c:
          cd \build
          dir
          tcc game.cpp
        conf: |
          [dosbox]
          memsize=256

          [cpu]
          cycles=max
          turbo=true

    - name: Show build directory contents
      run: ls -la build

    - name: Archive result
      run: |
        BASENAME="${RENAMED_FILENAME%.*}"
        EXENAME="${BASENAME^^}.EXE"
        mkdir -p output
        cp build/$EXENAME output/
        zip -j output.zip output/*

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: turbosnake-exe
        path: output.zip
